version: '3.7'

services:
    backend:
        container_name: backend
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - SERVER_PORT=${SERVER_PORT}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_HOST=${DATABASE_HOST}
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ./:/usr/src/app:cached
        command: yarn start:watch
        env_file:
            - .env
        networks:
            - webnet

    postgres:
        container_name: postgres
        restart: always
        image: postgres:12.4-alpine
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_DB: ${DATABASE_NAME}
            PG_DATA: ./var/lib/postgresql/data
        ports:
            - ${DATABASE_PORT}:${DATABASE_PORT}
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - webnet

networks:
    webnet:

volumes:
    pgdata: